main:
  - name: Inicio
    url: /
    weight: 10

  - name: Investigación
    url: research
    weight: 20

  - name: Equipo
    url: people
    weight: 30

  - name: Publicaciones
    url: publication
    weight: 40

  - name: Proyectos
    url: project
    weight: 50

  - name: Infraestructura
    url: infrastructure
    weight: 60

  - name: Impacto
    url: impact
    weight: 70

  - name: Contacto
    url: contact
    weight: 80